version: "3.9"
services:
  ocsf-server:
    build: .
    ports: 
      - "${OCSF_SERVER_PORT:-8080}:8080"
    working_dir: /ocsf-server
    environment:
      - "SCHEMA_DIR=/app/schema"
    volumes:
        - "./:/ocsf-server:z"
        - "${SCHEMA_PATH:-./modules/schema}:/app/schema:z"

  ocsf-elixir:
    image: "elixir:${ELIXIR_VERSION:-otp-25-alpine}"
    working_dir: /ocsf-server
    entrypoint: /docker-entrypoint-dev.sh
    command: echo # dummy command
    environment:
      - "SCHEMA_DIR=/app/schema"
      - "MIX_HOME=/ocsf-server/.mix"
    volumes:
        - "./:/ocsf-server:z"
        - "${SCHEMA_PATH:-./modules/schema}:/app/schema:z"
        - "./docker-entrypoint-dev.sh:/docker-entrypoint-dev.sh"
